### ISSUE TITLE
SID dependency

### ISSUE THREAD

**Issue by dirknbr** [nicolagnecco/causalXtreme#3]
does the package depend on SID which has been removed from cran?

**Comment by nicolagnecco** [comment]
Thanks for the heads-up. 

Yes, the package depends on `SID`, which was removed from CRAN.

I am now considering whether it is better to include the needed `SID` functions in `causalXtreme` or make `SID` available on CRAN again.

In the meantime, I modified the `DESCRIPTION` file, so the package retrieves `SID` from https://github.com/cran/SID.
